services:
  - type: web
    name: smile-cafe-pos
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "from app import app, db; with app.app_context(): db.create_all()" && gunicorn app:app
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5000
